// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Conversa.Net.Xmpp")]
[assembly: AssemblyProductAttribute("conversa")]
[assembly: AssemblyDescriptionAttribute("Portable XMPP protocol")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
